export type PortfolioItem = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

export const PORTFOLIO: PortfolioItem[] = [
  { src: "/images/portfolio/p01.png", alt: "Huruf timbul toko", width: 300, height: 300 },
  { src: "/images/portfolio/p02.png", alt: "Neon sign branding", width: 300, height: 300 },
  { src: "/images/portfolio/p03.png", alt: "Neon box akrilik", width: 300, height: 300 },
  { src: "/images/portfolio/p04.jpg", alt: "Papan signage toko", width: 300, height: 300 },
  { src: "/images/portfolio/p05.jpg", alt: "Neon box toko", width: 300, height: 300 },
  { src: "/images/portfolio/p06.jpg", alt: "Signage toko", width: 300, height: 300 },
  { src: "/images/portfolio/p07.jpg", alt: "Billboard", width: 300, height: 200 },
  { src: "/images/portfolio/p08.jpg", alt: "Papan nama toko", width: 300, height: 300 },
  { src: "/images/portfolio/p09.jpg", alt: "Signage restoran", width: 300, height: 169 },
  { src: "/images/portfolio/p10.jpg", alt: "Huruf timbul restoran", width: 225, height: 300 },
  { src: "/images/portfolio/p11.jpg", alt: "Billboard jalan", width: 300, height: 142 },
  { src: "/images/portfolio/p12.jpg", alt: "Papan toko", width: 225, height: 300 },
  { src: "/images/portfolio/p13.jpg", alt: "Neon box usaha", width: 300, height: 225 },
  { src: "/images/portfolio/p14.jpg", alt: "Signage kedai", width: 300, height: 225 },
  { src: "/images/portfolio/p15.jpg", alt: "Neon box custom", width: 300, height: 258 },
  { src: "/images/portfolio/p16.jpg", alt: "Papan nama warung", width: 225, height: 300 },
  { src: "/images/portfolio/p17.jpg", alt: "Huruf timbul custom", width: 142, height: 300 },
  { src: "/images/portfolio/p18.jpg", alt: "Neon sign kafe", width: 225, height: 300 },
  { src: "/images/portfolio/p19.jpg", alt: "Signage minimarket", width: 225, height: 300 },
  { src: "/images/portfolio/p20.jpg", alt: "Neon box toko", width: 300, height: 225 },
  { src: "/images/portfolio/p21.jpg", alt: "Papan tanda usaha", width: 169, height: 300 },
  { src: "/images/portfolio/p22.jpg", alt: "Billboard pinggir jalan", width: 300, height: 169 },
  { src: "/images/portfolio/p23.jpg", alt: "Huruf timbul toko", width: 225, height: 300 },
  { src: "/images/portfolio/p24.jpg", alt: "Papan nama klinik", width: 225, height: 300 },
  { src: "/images/portfolio/p25.jpg", alt: "Neon sign barbershop", width: 225, height: 300 },
  { src: "/images/portfolio/p26.jpg", alt: "Signage toko retail", width: 225, height: 300 },
  { src: "/images/portfolio/p27.jpg", alt: "Neon box restoran", width: 300, height: 225 },
  { src: "/images/portfolio/p28.jpg", alt: "Huruf timbul kafe", width: 225, height: 300 },
  { src: "/images/portfolio/p29.jpg", alt: "Papan nama toko", width: 225, height: 300 },
  { src: "/images/portfolio/p30.jpg", alt: "Neon box custom", width: 300, height: 225 },
  { src: "/images/portfolio/p31.jpg", alt: "Signage apotek", width: 225, height: 300 },
  { src: "/images/portfolio/p32.jpg", alt: "Huruf timbul custom", width: 169, height: 300 },
  { src: "/images/portfolio/p33.jpg", alt: "Billboard reklame", width: 300, height: 169 },
  { src: "/images/portfolio/p34.jpg", alt: "Neon box toko", width: 300, height: 225 },
  { src: "/images/portfolio/p35.jpg", alt: "Signage usaha", width: 300, height: 225 },
  { src: "/images/portfolio/p36.jpg", alt: "Papan tanda kafe", width: 225, height: 300 },
  { src: "/images/portfolio/p37.jpg", alt: "Neon box kuliner", width: 300, height: 225 },
  { src: "/images/portfolio/p38.jpg", alt: "Huruf timbul toko", width: 300, height: 225 },
  { src: "/images/portfolio/p39.jpg", alt: "Neon sign shop", width: 225, height: 300 },
  { src: "/images/portfolio/p40.jpg", alt: "Papan nama toko", width: 225, height: 300 },
  { src: "/images/portfolio/p41.jpg", alt: "Signage kedai kopi", width: 225, height: 300 },
  { src: "/images/portfolio/p42.jpg", alt: "Huruf timbul salon", width: 225, height: 300 },
  { src: "/images/portfolio/p43.jpg", alt: "Neon box toko", width: 225, height: 300 },
  { src: "/images/portfolio/p44.jpg", alt: "Papan toko custom", width: 225, height: 300 },
  { src: "/images/portfolio/p45.jpg", alt: "Neon sign barbershop", width: 225, height: 300 },
  { src: "/images/portfolio/p46.jpg", alt: "Signage toko", width: 300, height: 225 },
  { src: "/images/portfolio/p47.jpg", alt: "Huruf timbul custom", width: 169, height: 300 },
  { src: "/images/portfolio/p48.jpg", alt: "Papan tanda usaha", width: 169, height: 300 },
];